import {
  AccountCircle,
  ContentPaste,
  Crop75,
  DateRange,
  Feed,
  Home,
  Language,
  Menu,
  Newspaper,
  Portrait,
} from '@mui/icons-material';

import { INavigationItem } from '@/types/navigations';

import { PERMISSIONS_ENUM } from '../enums';

export const NAVIGATIONS: INavigationItem[] = [
  // {
  //   title: 'Dashboard',
  //   icon: <Window />,
  //   isChildren: false,
  //   path: '/dashboard',
  // },
  {
    title: 'Quản lý người dùng',
    icon: <AccountCircle />,
    isChildren: false,
    path: '/users',
    code: PERMISSIONS_ENUM.USERS,
  },
  {
    title: 'Quản lý trang chủ',
    icon: <Home />,
    isChildren: true,
    path: '/homepage',
    code: PERMISSIONS_ENUM.HOMEPAGE,
    children: [
      {
        title: 'Banner',
        icon: '',
        isChildren: false,
        path: '/homepage/banners',
        level: 1,
      },
      {
        title: 'Thông báo',
        icon: '',
        isChildren: false,
        path: '/homepage/notifications',
        level: 1,
      },
      {
        title: 'Sự kiện trong tháng',
        icon: '',
        isChildren: false,
        path: '/homepage/events',
        level: 1,
      },
      {
        title: 'Liên kết',
        icon: '',
        isChildren: false,
        path: '/homepage/links',
        level: 1,
      },
    ],
  },
  {
    title: 'Quản lý thông tin',
    icon: <Feed />,
    isChildren: true,
    path: '/information',
    code: PERMISSIONS_ENUM.INFORMATION,
    children: [
      {
        title: 'Khoa và bộ môn',
        icon: '',
        isChildren: true,
        path: '/information/section',
        level: 1,
        children: [
          {
            title: 'Nhóm khoa',
            icon: '',
            isChildren: false,
            path: '/information/section-groups',
            level: 2,
          },
          {
            title: 'Khoa',
            icon: '',
            isChildren: false,
            path: '/information/sections',
            level: 2,
          },
        ],
      },
      {
        title: 'Phòng ban chức năng',
        icon: '',
        isChildren: false,
        path: '/information/departments',
        level: 1,
      },
      {
        title: 'Trung tâm và Viện',
        icon: '',
        isChildren: false,
        path: '/information/institutes',
        level: 1,
      },
      {
        title: 'Đảng và Đoàn thể',
        icon: '',
        isChildren: false,
        path: '/information/parties',
        level: 1,
      },
    ],
  },
  {
    title: 'Quản lý Menu',
    icon: <Menu />,
    isChildren: true,
    path: '/menu',
    code: PERMISSIONS_ENUM.MENU,
    children: [
      {
        title: 'Trang',
        icon: '',
        isChildren: false,
        path: '/menu/pages',
        level: 1,
      },
      {
        title: 'Danh mục',
        icon: '',
        isChildren: false,
        path: '/menu/folders',
        level: 1,
      },
      {
        title: 'Menu',
        icon: '',
        isChildren: false,
        path: '/menu/menus',
        level: 1,
      },
    ],
  },
  {
    title: 'Quản lý nội dung',
    icon: <ContentPaste />,
    isChildren: false,
    path: '/posts',
    code: PERMISSIONS_ENUM.POSTS,
  },
  {
    title: 'Lịch công tác',
    icon: <DateRange />,
    isChildren: false,
    path: '/schedules',
    code: PERMISSIONS_ENUM.SCHEDULES,
  },
  {
    title: 'Duyệt tin',
    icon: <Newspaper />,
    isChildren: false,
    path: '/approve',
    code: PERMISSIONS_ENUM.APPROVE,
  },
  {
    title: 'Quản lý nhân sự',
    icon: <Portrait />,
    isChildren: true,
    path: '/staff',
    code: PERMISSIONS_ENUM.STAFF,
    children: [
      {
        title: 'Nhân sự',
        icon: '',
        isChildren: false,
        path: '/staff/employees',
        level: 1,
      },
      {
        title: 'Chức vụ',
        icon: '',
        isChildren: false,
        path: '/staff/positions',
        level: 1,
      },
    ],
  },
  {
    title: 'Footer',
    icon: <Crop75 />,
    isChildren: true,
    path: '/footer',
    code: PERMISSIONS_ENUM.FOOTER,
    children: [
      {
        title: 'Địa chỉ',
        icon: '',
        isChildren: false,
        path: '/footer/address',
        level: 1,
      },
      {
        title: 'Social',
        icon: '',
        isChildren: false,
        path: '/footer/socials',
        level: 1,
      },
      {
        title: 'Category',
        icon: '',
        isChildren: false,
        path: '/footer/categories',
        level: 1,
      },
    ],
  },
  {
    title: 'Ngôn ngữ',
    icon: <Language />,
    isChildren: false,
    path: '/languages',
    code: PERMISSIONS_ENUM.LANGUAGE,
  },
];
