import {
  AccountCircle,
  ContentPaste,
  Crop75,
  DateRange,
  Feed,
  Home,
  Language,
  Menu,
  Newspaper,
  Portrait,
} from '@mui/icons-material';

import { INavigationItem } from '@/types/navigation';

export const NAVIGATIONS: INavigationItem[] = [
  // {
  //   title: 'Dashboard',
  //   icon: <Window />,
  //   isChildren: false,
  //   path: '/dashboard',
  // },
  {
    title: 'Quản lý người dùng',
    icon: <AccountCircle />,
    isChildren: false,
    path: '/users',
  },
  {
    title: 'Quản lý trang chủ',
    icon: <Home />,
    isChildren: true,
    path: '/homepage',
    children: [
      {
        title: 'Banner',
        icon: '',
        isChildren: false,
        path: '/homepage/banners',
        level: 1,
      },
      {
        title: 'Thông báo',
        icon: '',
        isChildren: false,
        path: '/homepage/notifications',
        level: 1,
      },
      {
        title: 'Sự kiện trong tháng',
        icon: '',
        isChildren: false,
        path: '/homepage/events',
        level: 1,
      },
      {
        title: 'Liên kết',
        icon: '',
        isChildren: false,
        path: '/homepage/links',
        level: 1,
      },
    ],
  },
  {
    title: 'Quản lý thông tin',
    icon: <Feed />,
    isChildren: true,
    path: '/informations',
    children: [
      {
        title: 'Khoa và bộ môn',
        icon: '',
        isChildren: true,
        path: '/informations/subjects',
        level: 1,
        children: [
          {
            title: 'Nhóm khoa',
            icon: '',
            isChildren: false,
            path: '/informations/subjects-group',
            level: 2,
          },
          {
            title: 'Khoa',
            icon: '',
            isChildren: false,
            path: '/informations/subjects-list',
            level: 2,
          },
        ],
      },
      {
        title: 'Phòng ban chức năng',
        icon: '',
        isChildren: false,
        path: '/informations/departments',
        level: 1,
      },
      {
        title: 'Trung tâm và Viện',
        icon: '',
        isChildren: false,
        path: '/informations/centers',
        level: 1,
      },
      {
        title: 'Đảng và Đoàn thể',
        icon: '',
        isChildren: false,
        path: '/informations/unions',
        level: 1,
      },
    ],
  },
  {
    title: 'Quản lý Menu',
    icon: <Menu />,
    isChildren: true,
    path: '/menu',
    children: [
      {
        title: 'Menu',
        icon: '',
        isChildren: false,
        path: '/menu/mainmenu',
        level: 1,
      },
      {
        title: 'Trang',
        icon: '',
        isChildren: false,
        path: '/menu/pages',
        level: 1,
      },
      {
        title: 'Danh mục',
        icon: '',
        isChildren: false,
        path: '/menu/categories',
        level: 1,
      },
    ],
  },
  {
    title: 'Quản lý nội dung',
    icon: <ContentPaste />,
    isChildren: false,
    path: '/contents',
  },
  {
    title: 'Lịch công tác',
    icon: <DateRange />,
    isChildren: false,
    path: '/schedule',
  },
  {
    title: 'Duyệt tin',
    icon: <Newspaper />,
    isChildren: false,
    path: '/approve',
  },
  {
    title: 'Quản lý nhân sự',
    icon: <Portrait />,
    isChildren: true,
    path: '/staff',
    children: [
      {
        title: 'Nhân sự',
        icon: '',
        isChildren: false,
        path: '/staff/personnels',
        level: 1,
      },
      {
        title: 'Chức vụ',
        icon: '',
        isChildren: false,
        path: '/staff/positions',
        level: 1,
      },
    ],
  },
  {
    title: 'Footer',
    icon: <Crop75 />,
    isChildren: false,
    path: '/footer',
  },
  {
    title: 'Ngôn ngữ',
    icon: <Language />,
    isChildren: false,
    path: '/languages',
  },
];
